const data = [
{
    id:1,
    jobTitle:" Content Writing",
    companyName:"MHLondon",
    companyImg:"https://internshala.com/static/images/common/new_internshala_logo.svg",
    location:"Work From Home",
    startDate:"Immediately",
    duration:"3 Months",
    stipend:"15000 /month",
    applyDate:"20 Oct' 21",
    guideline:"",
    internship:"Internship",
    partTime:"Part-time",
},
{
    id:2,
    jobTitle:" Content Writing",
    companyName:"MHLondon",
    companyImg:"https://internshala.com/static/images/common/new_internshala_logo.svg",
    location:"Work From Home",
    startDate:"Immediately",
    duration:"3 Months",
    stipend:"15000 /month",
    applyDate:"20 Oct' 21",
    icon:<i class="fas fa-home"></i>,
    guideline:"The hiring for this internship will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves",
    internship:"Internship",
    partTime:"",
},
{
    id:3,
    jobTitle:" Content Writing",
    companyName:"MHLondon",
    companyImg:"https://internshala.com/static/images/common/new_internshala_logo.svg",
    location:"Work From Home",
    startDate:"Immediately",
    duration:"3 Months",
    stipend:"15000 /month",
    applyDate:"20 Oct' 21",
    guideline:"",
    internship:"Internship",
    partTime:"Part-time",
},
{
    id:4,
    jobTitle:" Content Writing",
    companyName:"MHLondon",
    companyImg:"https://internshala.com/static/images/common/new_internshala_logo.svg",
    location:"Work From Home",
    startDate:"Immediately",
    duration:"3 Months",
    stipend:"15000 /month",
    applyDate:"20 Oct' 21",
    guideline:"",
    internship:"Internship",
    partTime:"Part-time",
},
{
    id:5,
    jobTitle:" Content Writing",
    companyName:"MHLondon",
    companyImg:"https://internshala.com/static/images/common/new_internshala_logo.svg",
    location:"Work From Home",
    startDate:"Immediately",
    duration:"3 Months",
    stipend:"15000 /month",
    applyDate:"20 Oct' 21",
    icon:<i class="fas fa-home"></i>,
    guideline:"The hiring for this internship will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves",
    internship:"Internship",
    partTime:"",
}
];

export default data;